### ISSUE TITLE
Telemetry property not being emitted

### ISSUE THREAD

**Issue by kavitham10** [microsoft/ads-extension-telemetry#30]
Hi @Charles-Gagnon , in the Sql-migration extension (login migration wizard), we are logging errorMessage string for a telemetry event called LoginMigrationError. It doesn’t contain any PII, just an error string, corresponding PR [here](https://github.com/microsoft/azuredatastudio/pull/22927). The property is not being emitted in the telemetry yet though (see Kusto query [here](https://dataexplorer.azure.com/clusters/ddazureclients/databases/ADS?query=H4sIAAAAAAAAA41TS0/cMBC+8yumuUAPaXZhAXFIpUpQCalboWbbHhAHN54EV7EdPN7dUvHjO0724awI6iWJPN/D82Umy6BAhMbWyoBWtRNeWQPonHV09E2sb1ZoPH26Lo5eYP2IDqE7+So0QmmNF8oQJPTUpDt2wlD849FIWClcQw7eknfK1Cd3zrbovEK6Pw6144f3O90Ou5csnpr5VvGn+iucTMC6Q9SXcPHIkJCICbdyzHUDULK33tBE2bU9wumrQ4KkH+joDVJptbbmAwNXPXDAV3RrSEmuMD8S23em+nrUmxeuRr94bnHMs0d4RgzM+CGMH8+krx9EQstfVDrV+rfjjFAHAt0rNPV/QTH8taAeBRXP5FHfhJEc02AUdahucIfXCCdz/uuiHs0txgRylm2Hco6Clo4xyeaamiqvjEdnRJM8QJ7DFCL8QWrvckiqcjI7nV1U6WRWnqezs0tMRXmO6enkQkyv8HJ6dVYlkGXwWTWsC1t1uNY8JP33nUO1wvUCyQeLyDAepBwq0RBGWq2zctnPNq8wcCPLxlNEL9Bx6t/bxgq5UJr1hW7hI89kbeFkKvfruVmR4NJv3W47uz8T5pTdfmPpB5H/A6kuAIthBAAA)). Can you please take a look and help enable the property 'errorMessage' to emit? Thank you.

**Comment by Charles-Gagnon** [comment]
Quick update, it seems like the property is being added and sent correctly (verified this with the current ADS stable). Looking into why it might not be showing up on the backend side...

**Comment by Charles-Gagnon** [comment]
Was backend data issue, verified that the property is being sent up correctly.
